---
- name: Running apt update
  apt: update_cache=yes

- name: Installing required packages
  apt: name={{item}} state=present
  with_items:
   - fail2ban
   - postgresql
   - postgresql-client
   - python3
   - virtualenv
   - virtualenvwrapper
   - git
   - python3-pip
   - rdiff-backup
   - libpq-dev
   - python3-psycopg2
   - uwsgi
   - uwsgi-emperor
   - uwsgi-plugin-python3
   - nginx-full