---
- name: Create ubuntu user
  user: name=felix shell=/bin/bash groups=admin # generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa
#- name: Read SSH public key
#   slurp: src=/home/felix/.ssh/id_rsa.pub
#   register: public_key
# - debug: msg="{{ public_key['content'] | b64decode }}"