---
- name: enable SSH forwarding for sudo
  lineinfile:
    dest: /etc/sudoers
    insertafter: '^#?\s*Defaults\s+env_keep\b'
    line: 'Defaults    env_keep += "SSH_AUTH_SOCK"'

- name: ensure github.com is a known host
  lineinfile:
    dest: /home/{{ user}}/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
#  become: true

- name: Clone repo
  git:
    repo: "{{ git_repo }}"
    dest: "{{ repo_dir }}"
    version: master
    accept_hostkey: yes
#    key_file: ~/.ssh/id_rsa.pub
#  become_user: felix
#
#
#- name: pull branch master
#  git:
#    repo={{ git_repo }}
#    dest={{ repo_dir }}
#    version={{ git_branch }}
#    clone=yes
#    accept_hostkey=yes
#    #    repo={{ repo_url }}/{{ repo }}.git